SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_01]

  Union all

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_02]

  Union all

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_03]

  Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_04]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_05]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_06]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_07]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_08]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_09]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_10]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_11]

   Union All

  SELECT [ProductID]
      ,[Barcode]
      ,[ProductName]
      ,[Category]
      ,[StoreID]
      ,[StoreName]
      ,[Province]
      ,[CashierName]
      ,[SaleDate]
      ,[Quantity]
      ,[UnitPrice]
      ,[TotalAmount]
  FROM [PnP_Store].[dbo].[pnp_sales_2025_12]